# Workflow [No identation required for naming the workflow]
name: Hello

# On tells when the workflow should run (Give identation by tab)
on: 
  workflow_dispatch:

# Job tells what the workflow should do, there can be one or more than one jobs, hence we write jobs
# job is an ibject so need idenattion

jobs: 
   # 1st job (give idenattion)
   say-hello:
   # Creates an emphermal conntainer with ubuntu running
   runs-on: ubuntu-latest
   # That emphermal container will have steps to execute, hence name those steps and use run: run has the command
   steps:
      - name: Say hello to everyone
      run: echo "Hello Dosto"

# Steps
# Should be inside the job

# Actions
# Should be inside the steps
